### PR TITLE
Suitable Title is added

### LINKED ISSUE #2: I dont like the HTML title that says "Kvakk-Sjakk"
As a first "issue", maybe this is a good start.

I would love an English title, can be anything.
It can likely be fixed in one line in the index.html file.
Anyone feeling creative about the title?

### PR DESCRIPTION
**Pull request by Asmit-Rai**
Title is added "Chess Grandmaster's Arena"

### CODE REVIEW

**Comment by emilbratt** [comment]
Hi @Asmit-Rai 

How did you find this [Issue](https://github.com/emilbratt/lonely-chess/issues/2)?
Did you search issues and sort by labels?
This one has label "good first issue"
..and I was expecting a PR from someone i know that just started learning Github.

Anyways,  I'll happily merge your PR and then add new easy issues for beginners.

**Comment by Asmit-Rai** [comment]
Thanks for merging.
Basically I filtered the labels and I found your issue..
Love from india

**Comment by emilbratt** [comment]
That's cool.
I wish you good luck on your future PR's and have a lovely weekend.

**Comment by Asmit-Rai** [comment]
Thanks, you too!

**Pull request merged**
